name: Link Checker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude-path node_modules './**/*.md' './**/*.html'
          fail: true
